name: Manaual Triger

on:
  workflow_dispatch:
 inputs:
 name:
 description: 'Name'
 type: String
 default: 'Test'
 age:
 descripation: "Age"
 type: number
 required :  true
 jobs:
 Manual:
 
    
 

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"
